spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tutorial_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
